baseurl = "https://axelvanherle.github.io/"
DefaultContentLanguage = "en"
title = "Axel Vanherle"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Electronics ICT Student."
  mainSections = ["post","posts"]
  logo = "img/icon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  
  
 ############################
## Comments
############################
[comments]
  # Comment provider:
  provider = "giscus"

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  # Configuration of giscus
  [comments.giscus]
    repo = "axelvanherle/axelvanherle.github.io" # Repo where the comments will live
    repo_id = "R_kgDOIxbphw" # Repo where the comments will live
    category = "Articles" # Repo where the comments will live
    category_id = "DIC_kwDOIxbph84CUdTq" # Repo where the comments will live
    mapping = "pathname" # How Utterances will match comment to page
    label = "comment" # Label applied to issue by utteranc.es bot
    theme = "light" # What theme to use
    reactions_enabled = 0

[Author]
  name = "Axel Vanherle"
  website = "https://axelvanherle.github.io/"
  email = "axelvanherle@outlook.com"
  github = "axelvanherle"
  linkedin = "axelvanherle"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
