baseurl = "https://axelvanherle.github.io/"
DefaultContentLanguage = "en"
title = "Axel Vanherle"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Electronics ICT Student."
  mainSections = ["post","posts"]
  logo = "img/icon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  
[params.giscus]
repo = "cdwilson/cdwilson.dev"
repoID = "R_kgDOGzJrfg"
category = "Articles"
categoryID = "DIC_kwDOGzJrfs4CP2TM"
mapping = "og:title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "light"
lang = "en"
loading = "lazy"

[Author]
  name = "Axel Vanherle"
  website = "https://axelvanherle.github.io/"
  email = "axelvanherle@outlook.com"
  github = "axelvanherle"
  linkedin = "axelvanherle"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
