baseurl = "https://axelvanherle.github.io/"
DefaultContentLanguage = "en"
title = "Axel Vanherle"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Electronics ICT Student."
  mainSections = ["post","posts"]
  logo = "img/icon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Axel Vanherle"
  website = "https://axelvanherle.github.io/"
  email = "axelvanherle@outlook.com"
  github = "axelvanherle"
  linkedin = "axelvanherle"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
    
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
    
[[menu.main]]
    name = "Archive"
    url = "page/archive/"
    weight = 3
